spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: redis-cache
    redis:
      cache-null-values: false
      time-to-live: 3600000
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: ${POSTGRES_SCHEMA}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        current_session_context_class: thread
        hbm2ddl:
          auto: validate
    open-in-view: false

weather:
  url:
    coordinates: https://api.openweathermap.org/data/2.5/weather
    cities: http://api.openweathermap.org/geo/1.0/direct
  appid: 5d396363e327c5e9790d86a1330585c8